name: parent_internet_lock
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

#-------- PACKAGES --------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  flutter_native_splash: ^2.4.1

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6

  # State Management
  get: ^4.6.6

  #-------- ./ PACKAGES END --------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

  #-------- LOCAL ASSETS --------#
  assets:
    - assets/
    - assets/logos/
    - assets/icons/
    - assets/images/

  #-------- LOCAL FONTS --------#
  fonts:
    - family: LexendDeca
      fonts:
        - asset: assets/fonts/LexendDeca-Light.ttf
          weight: 300
        - asset: assets/fonts/LexendDeca-Regular.ttf
          weight: 400
        - asset: assets/fonts/LexendDeca-Medium.ttf
          weight: 500
        - asset: assets/fonts/LexendDeca-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/LexendDeca-Bold.ttf
          weight: 700