name: parent_internet_lock
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

#-------- PACKAGES --------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.2.2
  lottie: ^3.1.2
  connectivity_plus: ^6.0.5
  flutter_native_splash: ^2.4.1
  flutter_smart_dialog: ^4.9.8+2
  flutter_local_notifications: ^17.2.3
  device_info_plus: ^11.1.0
  qr_flutter: ^4.1.0
  qr_code_scanner_plus: ^2.0.8+1

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6
  pinput: ^5.0.0

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  firebase_messaging: ^15.1.3

  #-------- ./ PACKAGES END --------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

  #-------- LOCAL ASSETS --------#
  assets:
    - assets/
    - assets/logos/
    - assets/icons/
    - assets/images/
    - assets/images/animations/

  #-------- LOCAL FONTS --------#
  fonts:
    - family: LexendDeca
      fonts:
        - asset: assets/fonts/LexendDeca-Light.ttf
          weight: 300
        - asset: assets/fonts/LexendDeca-Regular.ttf
          weight: 400
        - asset: assets/fonts/LexendDeca-Medium.ttf
          weight: 500
        - asset: assets/fonts/LexendDeca-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/LexendDeca-Bold.ttf
          weight: 700